AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB table and SNS topic for SOAR metadata and alerts

Resources:

  ThreatMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ThreatMetadata
      AttributeDefinitions:
        - AttributeName: FindingID
          AttributeType: S
      KeySchema:
        - AttributeName: FindingID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  SecurityAlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: SecurityAlertTopic

Outputs:

  TableName:
    Description: Name of the DynamoDB table
    Value: !Ref ThreatMetadataTable

  SNSTopicARN:
    Description: ARN of the SNS topic
    Value: !Ref SecurityAlertTopic
