AWSTemplateFormatVersion: '2010-09-09'
Description: EventBridge rule for detecting Web Login Abuse and triggering Lambda containment

Resources:
  WebLoginAbuseRule:
    Type: AWS::Events::Rule
    Properties:
      Name: WebLoginAbuseTrigger
      Description: Trigger Lambda on detection of 5+ failed web login attempts
      EventPattern:
        source:
          - custom.web.logs
        detail-type:
          - Web Login Abuse Alert
      State: ENABLED
      Targets:
        - Arn: arn:aws:lambda:<ACCOUNT_REGION>:<AWS_ACCOUNT_ID>:function:WebLoginAbuseResponder
          Id: WebLoginAbuseResponderTarget

  PermissionForEventToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: arn:aws:lambda:<ACCOUNT_REGION>:<AWS_ACCOUNT_ID>:function:WebLoginAbuseResponder
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - WebLoginAbuseRule
          - Arn
